### ISSUE TITLE
Gravatar regression in SeaMonkey 2.53.5.1

### ISSUE THREAD

**Issue by JohnDDuncanIII** [JohnDDuncanIII/MessageFaces#6]
The fix for https://github.com/JohnDDuncanIII/messagefaces/issues/4 and/or a change in SeaMonkey `2.53.5.1` (or earlier) and deployed in https://github.com/JohnDDuncanIII/messagefaces/releases/tag/1.3.1 is causing a refresh loop to occur when we render the Gravatar PNG into the `messagepanebox` under certain circumstances.

If this occurs for you, please disable `Load face images from gravatar.com`.

I will try to fix this as soon as possible.

**Comment by stanio** [comment]
Yep, noticed it yesterday, but hadn't had a chance to look at it in detail and report it.  Seem you've noticed it also, already.

**Comment by JohnDDuncanIII** [comment]
@stanio, sorry for the delay — this is fixed in https://github.com/JohnDDuncanIII/messagefaces/releases/tag/1.3.2.

**Comment by stanio** [comment]
Hey John – thank you very much!  I greatly appreciate you're finding time to fix bugs in the extension as I'm still using it. 😃
